#:schema node_modules/wrangler/config-schema.json
name = "cloudflare-serverless-munki"
main = "src/index.ts"
compatibility_date = "2024-08-06"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "MUNKI_BUCKET"
bucket_name = "munki"
